// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.robot_manager;

public enum RobotFlag {
  WAIT_SPEAKER_SHOT,
  SPEAKER_SHOT,
  FORCE_SPEAKER_SHOT,
  WAIT_AMP_SHOT,
  AMP_SHOT,
  WAIT_SUBWOOFER_SHOT,
  SUBWOOFER_SHOT,
  WAIT_PODIUM_SHOT,
  PODIUM_SHOT,
  INTAKE,
  STOP_INTAKING,
  OUTTAKE_SHOOTER,
  WAIT_SHOOTER_AMP,
  SHOOTER_AMP,
  OUTTAKE,
  PRESET_RIGHT,
  PRESET_LEFT,
  PRESET_MIDDLE,
  PRESET_3,
  PREPARE_PRESET_RIGHT,
  PREPARE_PRESET_LEFT,
  PREPARE_PRESET_MIDDLE,
  PREPARE_PRESET_3,
  STOW,
  STOP_SHOOTING,
  IDLE_NO_GP,
  UNJAM,
  CLIMB_1_LINEUP_OUTER,
  CLIMB_2_LINEUP_INNER,
  CLIMB_3_LINEUP_FINAL,
  CLIMB_4_HANGING,
  CLIMB_5_HANGING_TRAP_SCORE,
  CLIMB_6_HANGING_ELEVATOR_FINISH,
  PRELOAD_NOTE,
  WAIT_FLOOR_SHOT,
  FLOOR_SHOT;
}
